## @knitr Pr3.1
library(knitr)
library(grDevices)
library(data.table)
library(ggplot2)
library(psych)
search()
library("rstudioapi")     
setwd(dirname(getActiveDocumentContext()$path))
getwd()
set.seed(42)
#Histograms
createHistograms<-function()
{
 h1<- hist(csvF[1:80,3],main="Number of Black pixels for letters", xlab="Black Pixels")
 #plot(h1) 
h2<- hist(csvF[81:140,3],main="Number of Black pixels for non letters", xlab="Black Pixels")
#plot(h2)  
h3<-hist(csvF[1:80,4],main="Number of rows with 1 black pixel for letters", xlab="rows with 1 Black Pixel")
#plot(h3)  

h4<-hist(csvF[81:140,4],main="Number of rows with 1 black pixel for non letters", xlab="rows with 1 Black Pixel")
#plot(h4) 
 h5<-hist(csvF[1:80,5],main="Number of cols with 1 black pixel for letters", xlab="cols with 1 Black Pixel")
 #plot(h5) 
 h6<-hist(csvF[81:140,5],main="Number of cols with 1 black pixel for non letters", xlab="cols with 1 Black Pixel")
 #plot(h6) 
 h7<-hist(csvF[1:80,6],main="Number of rows with 3 black pixels or more for letters", xlab="rows with 3+ Black Pixels")
 #plot(h7) 
 h8<-hist(csvF[81:140,6],main="Number of cols with 3 black pixels or more for non letters", xlab="rows with 3+ Black Pixels")
 #plot(h8) 
 h9<-hist(csvF[1:80,7],main="Number of cols with 3 black pixels or more for letters", xlab="cols with 3+ Black Pixels")
 #plot(h9) 
 h10<-hist(csvF[81:140,7],main="Number of cols with 3 black pixels or more for non letters", xlab="cols with 3+ Black Pixels")
 #plot(h10) 
 h11<-hist(csvF[1:80,8],main="aspect ratio for letters", xlab="ascept ratio")
 #plot(h11) 
 h12<-hist(csvF[81:140,8],main="aspect ratio for non letters", xlab="ascept ratio")
#plot(h12)
 }

createSummaryStats<-function()
{
print("Summary stats for no. of black pixels in letters")
print(summary(csvF[1:80,3]))
print("Summary stats for no. of black pixels in non letters")
print(summary(csvF[81:140,3]))
print("Summary stats for no. of rows with 1 black pixel in letters")
print(summary(csvF[1:80,4]))
print("Summary stats for no. of rows with 1 black pixel in non letters")
print(summary(csvF[81:140,4]))
print("Summary stats for no. of cols with 1 black pixel in letters")
print(summary(csvF[1:80,5]))
print("Summary stats for no. of cols with 1 black pixel in non letters")
print(summary(csvF[81:140,5]))
print("Summary stats for no. of rows with 3+ black pixel in letters")
print(summary(csvF[1:80,6]))
print("Summary stats for no. of rows with 3+ black pixel in letters")
print(summary(csvF[81:140,6]))
print("Summary stats for no. of cols with 3+ black pixel in letters")
print(summary(csvF[1:80,7]))
print("Summary stats for no. of cols with 3+ black pixel in nonletters")
print(summary(csvF[81:140,7]))
print("Summary stats for  ascept ratio for letters")
print(summary(csvF[1:80,8]))
print("Summary stats for  ascept ratio for nonletters")
print(summary(csvF[81:140,8]))
print("Summary stats for  all neighs with no black pixels for letters")
print(summary(csvF[1:80,9]))
print("Summary stats for  all neighs with no black pixels for nonletters")
print(summary(csvF[81:140,9]))
print("Summary stats for  above neighs with no black pixels for letters")
print(summary(csvF[1:80,10]))
print("Summary stats for  above neighs with no black pixels for nonletters")
print(summary(csvF[81:140,10]))
print("Summary stats for  below neighs with no black pixels for letters")
print(summary(csvF[1:80,11]))
print("Summary stats for  below neighs with no black pixels for nonletters")
print(summary(csvF[81:140,11]))
print("Summary stats for  left neighs with no black pixels for letters")
print(summary(csvF[1:80,12]))
print("Summary stats for  left neighs with no black pixels for nonletters")
print(summary(csvF[81:140,12]))
print("Summary stats for  right neighs with no black pixels for letters")
print(summary(csvF[1:80,13]))
print("Summary stats for  right neighs with no black pixels for nonletters")
print(summary(csvF[81:140,13]))
print("Summary stats for  horiz neighs with no black pixels for letters")
print(summary(csvF[1:80,14]))
print("Summary stats for  horiz neighs with no black pixels for nonletters")
print(summary(csvF[81:140,14]))
print("Summary stats for  vert neighs with no black pixels for letters")
print(summary(csvF[1:80,15]))
print("Summary stats for  vert neighs with no black pixels for nonletters")
print(summary(csvF[81:140,15]))
print("Summary stats for  connected areas for letters")
print(summary(csvF[1:80,16]))
print("Summary stats for  connected areas for nonletters")
print(summary(csvF[81:140,16]))
print("Summary stats for  eyes for letters")
print(summary(csvF[1:80,17]))
print("Summary stats for  eyes for nonletters")
print(summary(csvF[81:140,17]))
print("Summary stats for  widest row for letters")
print(summary(csvF[1:80,18]))
print("Summary stats for  widest row for nonletters")
print(summary(csvF[81:140,18]))
  #Histogram for 3 features
  x1<-csvF[1:80,3]
  x2<-csvF[81:140,3]
  theme_set(theme_bw())
  df <- data.table(k=c(x1,x2),label=c(rep('letters'),rep('non letters')))
  gr1<- ggplot()+geom_histogram(aes(x=x1,fill="blue"),breaks=hist(x1,plot=F)$breaks,alpha=0.7)+geom_histogram(aes(x=x2,fill="darkgreen"),breaks=hist(x2,plot=F)$breaks,alpha=0.7)
  gr1<-gr1 + xlab("Number of black Pixels")+ylab("occurances")+ggtitle("Number of Black pixels in images")+theme(plot.title = element_text(hjust=0.5))
  gr1<-gr1+ scale_fill_manual(values = c("blue","darkgreen"),name="Symbols",labels=c("letters","Non-Letters"))
  plot(gr1)
  x1<-csvF[1:80,10]
  x2<-csvF[81:140,10]
  gr1<- ggplot()+geom_histogram(aes(x=x1,fill="blue"),breaks=hist(x1,plot=F)$breaks,alpha=0.7)+geom_histogram(aes(x=x2,fill="darkgreen"),breaks=hist(x2,plot=F)$breaks,alpha=0.7)
  gr1<-gr1 + xlab("Number of black pixels above")+ylab("occurances")+ggtitle("Above neighbours with no black pixels")+theme(plot.title = element_text(hjust=0.5))
  gr1<-gr1+ scale_fill_manual(values = c("blue","darkgreen"),name="Symbols",labels=c("letters","Non-Letters"))
  plot(gr1)
  x1<-csvF[1:80,17]
  x2<-csvF[81:140,17]
  gr1<- ggplot()+geom_histogram(aes(x=x1,fill="blue"),breaks=hist(x1,plot=F)$breaks,alpha=0.7)+geom_histogram(aes(x=x2,fill="darkgreen"),breaks=hist(x2,plot=F)$breaks,alpha=0.7)
  gr1<-gr1 + xlab("eyes")+ylab("occurances")+ggtitle("eyes")+theme(plot.title = element_text(hjust=0.5))
  gr1<-gr1+ scale_fill_manual(values = c("blue","darkgreen"),name="Symbols",labels=c("letters","Non-Letters"))
  plot(gr1)
}
statsAnalyses<-function()
{
  #find the hypotheses- significant difference between letters and non-letters 
  # using the analysis which features are most useful to discriminate whether an image is a letter or a non-letter
  
  #-----Analysis-----

  #Skews
  skewsTab<-matrix(,ncol = 2,byrow = TRUE)
  colnames(skewsTab)<-c('letters','Non letters')
  skews<-c(skew(csvF[1:80,3]))
  skews<-append(skews,skew(csvF[81:140,3]))
  skewsTab<-rbind(skewsTab,skews)
  skews<-c(skew(csvF[1:80,4]))
  skews<-append(skews,skew(csvF[81:140,4]))
  skewsTab<-rbind(skewsTab,skews)
  skews<-c(skew(csvF[1:80,5]))
  skews<-append(skews,skew(csvF[81:140,5]))
  skewsTab<-rbind(skewsTab,skews)
  skews<-c(skew(csvF[1:80,6]))
  skews<-append(skews,skew(csvF[81:140,6]))
  skewsTab<-rbind(skewsTab,skews)
  skews<-c(skew(csvF[1:80,7]))
  skews<-append(skews,skew(csvF[81:140,7]))
  skewsTab<-rbind(skewsTab,skews)
  skews<-c(skew(csvF[1:80,8]))
  skews<-append(skews,skew(csvF[81:140,8]))
  skewsTab<-rbind(skewsTab,skews)
  skews<-c(skew(csvF[1:80,9]))
  skews<-append(skews,skew(csvF[81:140,9]))
  skewsTab<-rbind(skewsTab,skews)
  skews<-c(skew(csvF[1:80,10]))
  skews<-append(skews,skew(csvF[81:140,10]))
  skewsTab<-rbind(skewsTab,skews)
  skews<-c(skew(csvF[1:80,11]))
  skews<-append(skews,skew(csvF[81:140,11]))
  skewsTab<-rbind(skewsTab,skews)
  skews<-c(skew(csvF[1:80,12]))
  skews<-append(skews,skew(csvF[81:140,12]))
  skewsTab<-rbind(skewsTab,skews)
  skews<-c(skew(csvF[1:80,13]))
  skews<-append(skews,skew(csvF[81:140,13]))
  skewsTab<-rbind(skewsTab,skews)
  skews<-c(skew(csvF[1:80,14]))
  skews<-append(skews,skew(csvF[81:140,14]))
  skewsTab<-rbind(skewsTab,skews)
  skews<-c(skew(csvF[1:80,15]))
  skews<-append(skews,skew(csvF[81:140,15]))
  skewsTab<-rbind(skewsTab,skews)
  skews<-c(skew(csvF[1:80,16]))
  skews<-append(skews,skew(csvF[81:140,16]))
  skewsTab<-rbind(skewsTab,skews)
  skews<-c(skew(csvF[1:80,17]))
  skews<-append(skews,skew(csvF[81:140,17]))
  skewsTab<-rbind(skewsTab,skews)
  skews<-c(skew(csvF[1:80,18]))
  skews<-append(skews,skew(csvF[81:140,18]))
  skewsTab<-rbind(skewsTab,skews)
  
  skewsTab <- as.table(skewsTab)

  rownames(skewsTab)<-c('','number of pixels','rows with 1 black pixel','cols with 1 black pixel','rows with 3 or more black pixels','cols with 3 or more black pixels','Aspect ratio','neighbours with 1 black pixel','no above neighbours with black pixels','no below neighbours with black pixels','no left neighbours with black pixels','no right neighbours with black pixels','no horiz neighbours with black pixels','no vert neighbours with black pixels','connected areas','eyes','custom')
  write.table(skewsTab,file="SkewStats.csv",quote = FALSE,sep=",")


#randomization test

  
  #box plot
  boxplot(csvF[1:80,3],csvF[81:140,3],main="BoxPlots for number of black pixels",ylab="Black Pixels",names = c("Letters","NonLetters"))
  boxplot(csvF[1:80,4],csvF[81:140,4],main="BoxPlots for rows with 1 black pixel",ylab="rows with 1 black pixels",names = c("Letters","NonLetters"))
  boxplot(csvF[1:80,5],csvF[81:140,5],main="BoxPlots for cols with 1 black pixel",ylab="cols with 1 black pixels",names = c("Letters","NonLetters"))
  boxplot(csvF[1:80,6],csvF[81:140,6],main="BoxPlots for rows with 3+ black pixel",ylab="rows with 3+ black pixels",names = c("Letters","NonLetters"))
  boxplot(csvF[1:80,7],csvF[81:140,7],main="BoxPlots for cols with 3+ black pixel",ylab="cols with 3+ black pixels",names = c("Letters","NonLetters"))
  boxplot(csvF[1:80,8],csvF[81:140,8],main="BoxPlots for ascept ratio",ylab="Ascept ratio",names = c("Letters","NonLetters"))
  boxplot(csvF[1:80,9],csvF[81:140,9],main="BoxPlots for one black pixel neighbour",ylab="one black pixel neighbour",names = c("Letters","NonLetters"))
  boxplot(csvF[1:80,10],csvF[81:140,10],main="BoxPlots for no black pixels above neighbour",ylab="no black pixels above neighbour",names = c("Letters","NonLetters"))
  boxplot(csvF[1:80,11],csvF[81:140,11],main="BoxPlots for no black pixels below neighbour",ylab="no black pixels below neighbour",names = c("Letters","NonLetters"))
  boxplot(csvF[1:80,12],csvF[81:140,12],main="BoxPlots for no black pixels left neighbour",ylab="no black pixels left neighbour" ,names = c("Letters","NonLetters"))
  boxplot(csvF[1:80,13],csvF[81:140,13],main="BoxPlots for no black pixels right neighbour",ylab="no black pixels right neighbour",names = c("Letters","NonLetters"))
  boxplot(csvF[1:80,14],csvF[81:140,14],main="BoxPlots for no black pixels horiz neighbour",ylab="no black pixels horiz neighbour",names = c("Letters","NonLetters"))
  boxplot(csvF[1:80,15],csvF[81:140,15],main="BoxPlots for no black pixels vert neighbour",ylab="no black pixels vert neighbour",names = c("Letters","NonLetters"))
  boxplot(csvF[1:80,16],csvF[81:140,16],main="BoxPlots for connected areas",ylab="connected areas")
  boxplot(csvF[1:80,17],csvF[81:140,17],main="BoxPlots for eyes",ylab="eyes")
  boxplot(csvF[1:80,18],csvF[81:140,18],main="BoxPlots for most black pixels in a row",ylab="Most black pixels in a row")
  
  #t-Tests for each feature
  print(t.test(csvF[1:80,3],csvF[81:140,3],alt="two.sided"))
  print(t.test(csvF[1:80,4],csvF[81:140,4],alt="two.sided"))
  print(t.test(csvF[1:80,5],csvF[81:140,5],alt="two.sided"))
  print(t.test(csvF[1:80,6],csvF[81:140,6],alt="two.sided"))
  print(t.test(csvF[1:80,7],csvF[81:140,7],alt="two.sided"))
  print(t.test(csvF[1:80,8],csvF[81:140,8],alt="two.sided"))
  print(t.test(csvF[1:80,9],csvF[81:140,9],alt="two.sided"))
  print(t.test(csvF[1:80,10],csvF[81:140,10],alt="two.sided"))
  print(t.test(csvF[1:80,11],csvF[81:140,11],alt="two.sided"))
  print(t.test(csvF[1:80,12],csvF[81:140,12],alt="two.sided"))
  print(t.test(csvF[1:80,13],csvF[81:140,13],alt="two.sided"))
  print(t.test(csvF[1:80,14],csvF[81:140,14],alt="two.sided"))
  print(t.test(csvF[1:80,15],csvF[81:140,15],alt="two.sided"))
  print(t.test(csvF[1:80,16],csvF[81:140,16],alt="two.sided"))
  print(t.test(csvF[1:80,17],csvF[81:140,17],alt="two.sided"))
  print(t.test(csvF[1:80,18],csvF[81:140,18],alt="two.sided"))

}
 
degreeOfLinAssoc<-function()
{
  cors<-as.table((cor(csvF[1:140,3:18])))
  write.table(na.omit(cors),file="correlations.csv",quote = FALSE,sep=",")
  #print(cors)
  plot(csvF[1:140,3],csvF[1:140,6], xlab="No. Black pixels",ylab="rows with 3 black pixels")
  abline()
  plot(csvF[1:140,4],csvF[1:140,14],xlab="rows with 1 black pixel",ylab="no black pixel neigh horiz")
  plot(csvF[1:140,5],csvF[1:140,9],xlab="cols with 1 black pixel",ylab="1 black pixel neighbour")
  plot(csvF[1:140,7],csvF[1:140,18],xlab="cols with 3+ black pixels",ylab="custom")
  plot(csvF[1:140,7],csvF[1:140,8],xlab="cols with 3+ black pixels",ylab="ascept ratio")
  plot(csvF[1:140,8],csvF[1:140,10],xlab="ascept ratio",ylab="no black pixel neigh above")
  plot(csvF[1:140,8],csvF[1:140,11],xlab="ascept ratio",ylab="no black pixel neigh below")
  plot(csvF[1:140,8],csvF[1:140,18],xlab="ascept ratio",ylab="custom")
  plot(csvF[1:140,7],csvF[1:140,10],xlab="cols with 3+ black pixels",ylab="no black pixel neigh above")
  plot(csvF[1:140,10],csvF[1:140,11],xlab="no black pixel neigh above",ylab="no black pixel neigh below")
  plot(csvF[1:140,10],csvF[1:140,18],xlab="no black pixel neigh above",ylab="custom")
  plot(csvF[1:140,11],csvF[1:140,18],xlab="no black pixel below above",ylab="custom")
  plot(csvF[1:140,12],csvF[1:140,13],xlab="no black pixel neigh left",ylab="no black pixel neigh right")
  plot(csvF[1:140,3],csvF[1:140,14],xlab="rows with 1 black pixel",ylab="no black pixel neigh horiz")
  
   }
csvF<-read.csv(file ="40293751_features.csv" ,header = TRUE)

#colnames(csvF)<-c("symbol","number",'fea1','fea2','fea3','fea4','fea5','fea6','fea7','fea8','fea9','fea10','fea11','fea12','fea13','fea14','fea15','fea16')

createHistograms()#Part1
## @knitr Pr3.2
createSummaryStats()#Part2
## @knitr Pr3.3
statsAnalyses()#Part3
## @knitr Pr3.4
degreeOfLinAssoc()#Part4



